server:
  port: 8085

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: userok
    password: p@ssw0rd
    queues:
      text-message-update: TEXT_MESSAGE_UPDATE
      doc-message-update: DOC_MESSAGE_UPDATE
      photo-message-update: PHOTO_MESSAGE_UPDATE
      answer-message: ANSWER_MESSAGE

  datasource:
    url: jdbc:postgresql://localhost:5432/pogreb
    username: userok
    password: p@ssw0rd
  jpa:
    generate-ddl: true

token: 7155991615:AAEhlGMfHyrz-IXQ4cZygBIZYJVxkuyNO3g

service:
  file_info:
    uri: https://api.telegram.org/tatamibot{token}/getFile?file_id={fileId}
  file_storage:
    uri: https://api.telegram.org/file/tatamibot{token}/{filePath}